### ISSUE TITLE
add support mouldking 13130 black diy module

### ISSUE THREAD

**Issue by J0EK3R** [J0EK3R/brickcontroller2#2]
@MiyouQ asked:
Great work! Will there be plans to support mouldking 13130 black diy module in the future?

**Comment by J0EK3R** [comment]
Bad news:
it seams that the black DIY hubs are using another bluetooth technique than the gray ones.
The gray ones just react on "bluetooth advertisements".
The black hubs can be connected as real bluetooth devices to your phone/tablet.

...and I could not find any shop to buy a black diy hub separatly without model

**Comment by MiyouQ** [comment]
> Bad news: it seams that the black DIY hubs are using another bluetooth technique than the gray ones. The gray ones just react on "bluetooth advertisements". The black hubs can be connected as real bluetooth devices to your phone/tablet.
> 
> ...and I could not find any shop to buy a black diy hub separatly without model

Is there anything I can do?

**Comment by J0EK3R** [comment]
> Is there anything I can do?

...send me a "black hub" ;) or a link where I can bye one...

Or replace your "black hubs" by the well-working grey ones.

**Comment by J0EK3R** [comment]
I found a shop in china and ordered a "black hub".
I hope my money isn't lost ..
We will see what I can do.

It seems that the "black hub" from Mould King is deprecated.

**Comment by MiyouQ** [comment]
> > Is there anything I can do?
> 
> ...send me a "black hub" ;) or a link where I can bye one...
> 
> Or replace your "black hubs" by the well-working grey ones.

[宇星600毫安新款13130利勃海尔黑色锂电池大容量拼装积木通用PF件](https://item.taobao.com/item.htm?spm=a21n57.1.item.2.4644523cPQ6KmF&priceTId=2147808717218312953997625e797f&utparam=%7B%22aplus_abtest%22:%221b8ddd359f09c972827a45b381abe4c6%22%7D&id=670894190099&ns=1&abbucket=2&skuId=4996566518237)

I found it on Taobao.

**Comment by MiyouQ** [comment]
> I found a shop in china and ordered a "black hub". I hope my money isn't lost .. We will see what I can do.
> 
> It seems that the "black hub" from Mould King is deprecated.

It appears to be the case. mouldking replaced it with 6.0 and 4.0 modules in 13130S.
emmmmmmm.......

**Comment by J0EK3R** [comment]
We have to wait till my ordered hubs arrive...

**Comment by J0EK3R** [comment]
Yesterday, two of the "black hubs" from MouldKing came the long way from China directly to my cave... ;)

I just added the support for the black MouldKing DIY Module...

[Release 3.5 J0EK3R Beta 0](https://github.com/J0EK3R/brickcontroller2/releases/tag/3.5_J0EK3R_Beta_0)

**Comment by MiyouQ** [comment]
> Yesterday, two of the "black hubs" from MouldKing came the long way from China directly to my cave... ;)
> 
> I just added the support for the black MouldKing DIY Module...
> 
> [Release 3.5 J0EK3R Beta 0](https://github.com/J0EK3R/brickcontroller2/releases/tag/3.5_J0EK3R_Beta_0)

I connected 3 black hub and everything is perfect. Thank you for your hard work. I can't wait to introduce this to my friends.

**Comment by J0EK3R** [comment]
You are welcome :)

**Comment by J0EK3R** [comment]
@MiyouQ 
A completely revised version is available here in this github project:
https://github.com/vicocz/brickcontroller2/releases

**Comment by MiyouQ** [comment]
> [@MiyouQ](https://github.com/MiyouQ) A completely revised version is available here in this github project: https://github.com/vicocz/brickcontroller2/releases

Thanks! The revised version has been working perfectly.
