### ISSUE TITLE
CaDA C51072W Race Car doesn't work

### ISSUE THREAD

**Issue by J0EK3R** [J0EK3R/brickcontroller2#3]
Connection to CaDA C51072W Race Car doesn't work.

**Comment by J0EK3R** [comment]
@GusFantasma
Can you please tell me what color your model has?
Is there a sticker on the bottom - mine has one with a big green 8.

Btw.: the CaDa race car doesn't "connect" - you can't see them as Bluetooth device - they are controlled one way by Advertisement telegrams.

**Comment by GusFantasma** [comment]
> @GusFantasma Can you please tell me what color your model has? Is there a sticker on the bottom - mine has one with a big green 8.
> 
> Btw.: the CaDa race car doesn't "connect" - you can't see them as Bluetooth device - they are controlled one way by Advertisement telegrams.

It´s the red one, C51072W, it have the 8 stickeR, I also have other models with the same sticker, wich seems like it a product ID rather than a model ID

**Comment by J0EK3R** [comment]
Hmmm...
I have the same one and just tested it successfully with my Version of the "BrickController 2" app.

To be shure:
If you press the magnifying glas right down the devices view of the app a lot of devices appear like "MouldKing..." and the "Cada C51072W"?
Then, if you select the Cada device and move the two sliders in the device view your car does not react?
You have the Cada app installed on the same Android device and it works?
Can you tell me the version of your BrickController app? (i-Button right down of Main View)?
Newest is "Version 3.5 J0EK3R Beta 1".

**Comment by GusFantasma** [comment]
> Hmmm... I have the same one and just tested it successfully with my Version of the "BrickController 2" app.
> 
> To be shure: If you press the magnifying glas right down the devices view of the app a lot of devices appear like "MouldKing..." and the "Cada C51072W"? Then, if you select the Cada device and move the two sliders in the device view your car does not react? You have the Cada app installed on the same Android device and it works? Can you tell me the version of your BrickController app? (i-Button right down of Main View)? Newest is "Version 3.5 J0EK3R Beta 1".


Yes, all devices including the cada appear 
When selecting the cada device it doesn't react, but appear status as connected
I have the Cada app installed, it works without problem
Current version is  "Version 3.5 J0EK3R Beta 1".

**Comment by J0EK3R** [comment]
Ok, seams that you are doing everything right. :)

The "connected status" in the app doesn't mean anything in this case (yet). Till now it works just one-way...

I run the Cada app and saw that it's waiting till the car was switched on. Hmmm... it's not just one-way communication.
I think that there is some kind of data exchanged on connect wich is then used in the controlling communication...
That makes things much more complicated...

I have to play around... ;)

**Comment by J0EK3R** [comment]
I ordered another Cada model to see the difference between the communication.
Perhaps I can figure out how the communication is working...
I played around with the Cada app: it seams that the choice of the model does not play any role - can you confirm that?

**Comment by GusFantasma** [comment]
Hi, indeed any model.works exactly the same. I also ordered a new one (yellow model) let me know if I can help you with any information. I'm not very tech savvy with Bluetooth communication but I learn if you need it.

I really appreciate it :)

**Comment by J0EK3R** [comment]
...indeed you could help me (and you) while waiting the ordered models to arrive... ;)
You could sniff some BT-traffic and post the telegrams here.

If you have another (Android) device and could install the app "nRF connect" from the app store then you would be able to sniff all the BT-traffic around your device.

Then start the app "nRF connect" on the second device and press "scan" - if you haven't any other apps running or BT-devices sending around you no BT-traffic should appear.

Then start the CaDa app and go to control view while your model is off - in the app "nRF connect" you should see one chart line in the scanner view adding (RSSI) values every second and one entry on the right side of the view (with a "connect" button).

If you open that entry by clicking it you should see more infos (i.e. Company: Reserved ID <0xC200>)...
I'm interested in that data - press button "RAW" then the button "copy" (right top) to copy that hex-value to clipboard and post it here.

Then start you engine (power on the model)...
Another chart line and a second entry (without "connect" button) should appear...
It should have "Company: Reserved ID <0xFFF0>"
That's the response telegram of your model device - please copy raw data and post it.

Then steer left and right and forward and backward in your CaDa app - a lot of new entries in the app "nRF connect" should appear.

They all have "Company: Reserved ID <0xC200>" - please post the RAW data...

And then please run my version of the BC-app - you should see similar BT-traffic when CaDa Model is selected and you move the sliders for the channels...
If not... did you give all necessary rights to the app...? ;)

**Comment by J0EK3R** [comment]
My ordered model hast arrived.
Like yours it doesn't work with my BC2 Version.
After a first look on Bluetooth communication I think it's more complicated than I thought...
Work in progress... ;)

**Comment by GusFantasma** [comment]
> My ordered model hast arrived. Like yours it doesn't work with my BC2 Version. After a first look on Bluetooth communication I think it's more complicated than I thought... Work in progress... ;)

Hi

I also got a new one, yellow version. However I'm not entirely sure of the device selected is the right one, there are many devices detected around. I'll try in another location.

**Comment by J0EK3R** [comment]
...I'm very deep in figuring out how communication works.
Your Bluetooth traffic won't really help - I've almost all I need except time... ;)

**Comment by J0EK3R** [comment]
I think I've solved the 10000 pieces puzzle of a dark sky...

[4.0 J0EK3R Beta 1](https://github.com/J0EK3R/brickcontroller2/releases/tag/4.0_J0EK3R_Beta_1)

I can control my two CaDA RaceCars by the app - at the same time! :)

Just press the scan button and power on your CaDA RaceCars - they should be found by the app and appear in the devices list.

**Comment by J0EK3R** [comment]
@GusFantasma 
A completely revised version is available here in this github project:
https://github.com/vicocz/brickcontroller2/releases
